name: Release Workflow

on:
  push:
    tags:
      - 'v*.*.*' # Trigger workflow on tags that start with 'v'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      
      - name: Install deps
        run: |
          go get github.com/atotto/clipboard
          go get github.com/charmbracelet/bubbles/key
          go get github.com/charmbracelet/bubbles/list
          go get github.com/charmbracelet/bubbletea
          go get github.com/charmbracelet/lipgloss
          go get github.com/mitchellh/go-ps

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        